[build]
base = "frontend" # Set the base directory for the frontend code
publish = "frontend/build" # Set the directory to publish (build output of frontend)
CI = "npm run build" # The command to build your frontend

[build.environment]
NODE_ENV = "production" # Set Node.js environment to production for building frontend

[[redirects]]
from = "/api/*" # Redirect API requests to the backend server
to = "http://localhost:8000/:splat"
status = 200

[[redirects]]
from = "/*" # Redirect all other requests to the frontend
to = "/index.html"
status = 200
